# This file contains all the keywords to remove from the consent title

removeWords = ["And",
            "with",
            "Related",
            "Conditions",
            "Only",
            "Disease-Specific",
            "Disease Specific",
            "General Research Use",
            "GRU",
            "Non-Profit Use",
            "Non Profit Use",
            "Not for Profit Use",
            "Publication",
            "Required",
            "NPU",
            "GSO",
            "methods",
            "or",
            "IRB",
            "RD",
            "MDS",
            "PUB",
            "PLCO",
            "EAGLE",
            "COL",
            "in",
            "all",
            "age",
            "groups",
            "other",
            "adults",
            "Exchange Area",
            "Research",
            "to",
            "use by PAGE study investigators only",
            "None",
            "Unrestricted",
            "Up for a Challenge",
            "LC",
            "its",
            "multiple"
            ]

keyList2 = ["GRU",
            "General Research",
            "General Research Use",
            "Research",
            "Health Research",
            "Medical Research",
            "Biomedical Research",
            "HMB",
            "Health medical biomedical research",
            "health/medical/biomedcal research",
            "health/medical/biomedical"]

keyList1 = ["Disease",
           "Disorder"]